apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-control-plane
spec:
  profile: default
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
    pilot:
      enabled: true
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      tracer:
        zipkin:
          address: zipkin.istio-system:9411
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: llm-gateway
  namespace: llm-applications
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: llm-service
  namespace: llm-applications
spec:
  hosts:
  - "*"
  gateways:
  - llm-gateway
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: llm-service
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: llm-service
  namespace: llm-applications
spec:
  host: llm-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 1024
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 30s
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: triton-inference-server
  namespace: llm-applications
spec:
  hosts:
  - triton-inference-server
  http:
  - route:
    - destination:
        host: triton-inference-server
        port:
          number: 8000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: triton-inference-server
  namespace: llm-applications
spec:
  host: triton-inference-server
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN 