apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-service
  namespace: llm-applications
  labels:
    app: llm-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm-service
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: llm-service
        version: v1
    spec:
      containers:
      - name: llm-service
        image: ${REGISTRY_URL}/llm-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: MODEL_PATH
          value: "/models/llm-model"
        - name: LOG_LEVEL
          value: "info"
        volumeMounts:
        - name: model-volume
          mountPath: /models
      volumes:
      - name: model-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: llm-service
  namespace: llm-applications
  labels:
    app: llm-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: llm-service
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm-service-ingress
  namespace: llm-applications
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: llm-service
            port:
              number: 80
</rewritten_file> 