apiVersion: v1
kind: Namespace
metadata:
  name: llm-applications
  labels:
    name: llm-applications
    environment: base
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: base 